### ISSUE TITLE
Cannot view pages/articles - getting REQUEST error, nil.json 

### ISSUE THREAD

**Issue by jonathanwilner** [ahungry/md4rd#11]
Hi,

Love the idea of the mode! I've been able to do the oAuth setup, but I can't actually view any links/articles. Each attempt to browse the list results in the following error:

`"REQUEST [error] Error (error) while connecting to http://reddit.com/nil.json"`

I am using Emacs 26.1 on Mac OS X High Sierra. I got the same error with the MELPA package and source.

**Comment by ahungry** [comment]
What happens if you try using it without the sign in mode?  Does it work?

That link format comes from the reddit API permalink property, which is apparently missing if its interpolating a nil value here.

**Comment by jonathanwilner** [comment]
Hi - tried it first without logging in. Got the same error.

**Comment by ahungry** [comment]
What is the md4rd-subs-active variable/defcustom set to for you ?  The default value?

**Comment by jonathanwilner** [comment]
Yes.

**Comment by kodemaan** [comment]
I believe this happens when you hit enter on the name of the subreddit, or when you hit enter on the name of a person in a post thread. I'm using spacemacs

**Comment by jonathanwilner** [comment]
Hi there - still getting the same thing, even when not hitting return and using "o" instead. Does anyone else either have this same problem - or have more success? 

Do you have any suggestions for debugging this?

**Comment by kodemaan** [comment]
When i hit enter on the dots is seems to work. 

![image](https://user-images.githubusercontent.com/4562514/42237934-3d8a81bc-7ecd-11e8-9fa1-025b5d9037af.png)

Here it is expanded
![image](https://user-images.githubusercontent.com/4562514/42237949-48830f44-7ecd-11e8-9e7a-639fa359570b.png)

It should probably still be addressed as a bug but that's the way I got it working

**Comment by jonathanwilner** [comment]
Using the dots works!

**Comment by mgcyung** [comment]
The same error. And nothing happens after hitting enter or "o" on the
dots.
