### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by thiennamdinh** [ahungry/md4rd#15]
Hi,

It would be really nice if comment bodies were indented. Currently, the first paragraph of the comment is indented according to the comment hierarchy, but successive paragraphs begin at the left window border.

![selection_001](https://user-images.githubusercontent.com/26100246/49488939-06a88600-f806-11e8-9eec-d3460d4f9365.png)

**Comment by ahungry** [comment]
Yes, that would be very nice - I wonder if there are any existing packages or functions in Emacs we can use to easily achieve this without writing a bunch of ad-hoc indentation code.

**Comment by ahungry** [comment]
Oh yea, I remember, this is the body content of the hierarchy mode (I had to add custom wrappers to pad labels over as much as needed, so will likely have to manual add newlines to the comment body or something.

**Comment by ahungry** [comment]
Ok, check out commit 3dc8641

**Comment by ahungry** [comment]
![md4rd-indented](https://user-images.githubusercontent.com/10437774/49562623-58c2d780-f8ea-11e8-9be1-c40964baa277.png)

**Comment by thiennamdinh** [comment]
Thanks for the quick response/fix time! The change does seem to be effective most of the time but seems to break down for a lot of posts as well, at least on my setup. Below is an example of it working for the first few comments but then deteriorating back to the original state 

![selection_003](https://user-images.githubusercontent.com/26100246/49635089-e15d7880-f9bb-11e8-8301-e32c86797181.png)

Is that the case for you? I'll try to debug a bit more to see if I can isolate the cause.

**Comment by ahungry** [comment]
Please try again, I had a bug in the implementation

**Comment by thiennamdinh** [comment]
Looks perfect to me now. Thanks for the great work!

**Comment by ahungry** [comment]
np!
