### ISSUE TITLE
Support for images / pictures?

### ISSUE THREAD

**Issue by Ambrevar** [ahungry/md4rd#19]
Many reddit post contain pictures.  It would be nice if md4rd could display them.
Maybe leverage `eww` / `shr` for the rendering?

**Comment by jdtron** [comment]
Almost two years went in since the opening of this issue.
Any idias or updates on this which are worth sharing?
I'd also appreciate viewing images in md4rd very much.

**Comment by ahungry** [comment]
Feel free to open up a PR adding this feature.
