### ISSUE TITLE
MD4RD and Emacspeak

### ISSUE THREAD

**Issue by devinprater** [ahungry/md4rd#21]
I am a blind user of Emacs, using Emacspeak to have content spoken to me. [Emacspeak](http://www.github.com/tvraman/emacspeak/) does this using Advice and speech servers connected to software speech systems. Usually, Emacs modes work well with Emacspeak, without needing more more tweaking. Md4Rd, though, doesn't seem to work all that well.
To reproduce this:
- git clone http://www.github.com/tvraman/emacspeak/
- cd emacspeak
- make config
- make emacspeak
- If on a Mac, skip to loading Emacs
- On Linux, make espeak
- Open .emacs.el and enter
(load-file "/Users/devinprater/emacspeak/lisp/emacspeak-setup.el")
- Emacspeak should load, and begin speaking, when this list is evaluated.
- Now, open Md4Rd with M-X md4rd
- Emacspeak says nothing, which is okay, sort of.
- Press N. Emacspeak says "[+], *expand node*."
- This doesn't give me much to go on, so I use the arrow keys. There, I get the ascii graphical thing, and the sub on the line.
- Press e. The sub is expanded, Emacspeak doesn't respond, which again is sort of okay, as we know we pressed e.
- Press down-arrow, Emacspeak reads the first, likely sticky, post in the sub.
- Press e again. Here's where things get completely useless. No matter Where I look, I cannot find the content, or comments, of the post. It's not in this buffer, there has been no new buffer created, nothing else is there.

So, any ideas? I'd really like to browse Reddit from the wonderful accessibility of Emacs, with no web clutter and nonsensical key bindings that Reddit thinks I'll like, which only winds up spitting out literal parts of the page anyway, as if the up-vote, down-vote, share, ... buttons are a part of the post.

**Comment by ahungry** [comment]
After you press e the second time, you're actually almost on another widget (this occurs because md4rd uses liberal nesting thanks to hierarchy mode (a supporting mode that allows collapsing and expanding nodes)).

If you were to resume your flow, and press M-f you should land on the first word after the first listing.  From here, you can press your o key to open the article at point, or press RET to view the comments for that posting.

If you were to press C-n, that would take you to the next listing under that subreddit.  

Please let me know if there is anything I can alter in the mode to make this type of navigation/interaction easier.

**Comment by devinprater** [comment]
Well, after I expand a post with RET, I still cannot see the comments in the post. Maybe Emacspeak has to be changed in order to work better with the underlying mode used here? If you want to look at its code, its at
http://www.github.com/traman/emacspeak/ <http://www.github.com/traman/emacspeak/>

I may ask about any possibilities on the Emacspeak mailing list, maybe some other blind people, who have much more programming experience than me, can tweak either Emacspeak or MD4RD to work better together.

**Comment by ahungry** [comment]
I want to work on this, however even with `emacs -Q /path/to/emacspeak-setup.el`, I run into errors when trying to do things like have emacspeak voice the text at point etc. (Ubuntu 18.04).

Any suggestions? 


```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  locate-file-internal
```
(it seems it can't find a binary it needs?  I did attempt to set DTK_PROGRAM to both espeak and espeak-ng (the actual binary I have available))
