### ISSUE TITLE
How to get OAuth refresh token

### ISSUE THREAD

**Issue by aladine** [ahungry/md4rd#24]
Hi there, 
I am following the instruction and go to reddit page to get the OAuth access token. However, I only got 1 token string. How do I get the refresh token. Without it, i get this error every hour:
```
md4rd: Failed to refresh the OAuth access token!
```

**Comment by anoduck** [comment]
Same issue. Completely clueless on how to discover the refresh token. I have a feeling that it must be recorded in the tmp files somewhere, but where that is I do not know. It is not very apparent how to do this.

@aladine Did you ever find out how to acquire the refresh token?

**Comment by aladine** [comment]
Probably this will help: 
https://not-an-aardvark.github.io/reddit-oauth-helper/

**Comment by ahungry** [comment]
Its stored in the variable `md4rd--oauth-refresh-token` within the package.

**Comment by ahungry** [comment]
That means it is not saved if you close Emacs, you will have to login again, unless you were to inspect the value of the variable and add it to your config (if you use use-package, maybe you will define a block similar to this):

```lisp
       (use-package md4rd :ensure t
         :config
         (add-hook 'md4rd-mode-hook 'md4rd-indent-all-the-lines)
         (setq md4rd-subs-active '(emacs lisp+Common_Lisp prolog clojure))
         (setq md4rd--oauth-access-token
	       "<omitted>")
         (setq md4rd--oauth-refresh-token
	       "<omitted>"))
```

**Comment by anoduck** [comment]
@aladine Thanks, that node.js script worked beautifully. It clearly explained the process and fetched everything needed. Big help.

**Comment by anoduck** [comment]
Thanks for closing this out @ahungry, I obviously forgot to. My apologies.
