### ISSUE TITLE
Symbol’s function definition is void: map

### ISSUE THREAD

**Issue by nyambol** [ahungry/md4rd#33]
`Fetching: /r/emacs/comments/q63uw1/orgroamui_file_previews_at_last/`
`error in process sentinel: md4rd--greentext: Symbol’s function definition is void: map`

It actually opened the first article *in the browser*, and then everything after that was broken. 

GNU Emacs 29.0.50 (build 1, x86_64-w64-mingw32) of 2021-10-12
`--with-native-compilation --without-dbus --without-pop`
Windows 10 Pro

Debugger if I click an article instead of using a key.
`Debugger entered--Lisp error: (void-function map)
  map(list md4rd--greentext-line ("Ah ty, for some reason the preview mode option just appeared, but it does work now!"))
  md4rd--greentext("Ah ty, for some reason the preview mode option jus...")
  (if (member \.author md4rd--fool-list) md4rd--fool-text (md4rd--greentext \.body))
  (format " (%s) → %s\n" \.score (if (member \.author md4rd--fool-list) md4rd--fool-text (md4rd--greentext \.body)))
  (insert (format " (%s) → %s\n" \.score (if (member \.author md4rd--fool-list) md4rd--fool-text (md4rd--greentext \.body))))
  (let ((\.score (cdr (assq 'score alist))) (\.author (cdr (assq 'author alist))) (\.body (cdr (assq 'body alist)))) (insert (format " (%s) → %s\n" \.score (if (member \.author md4rd--fool-list) md4rd--fool-text (md4rd--greentext \.body)))))
  (let ((alist comment)) (let ((\.score (cdr (assq 'score alist))) (\.author (cdr (assq 'author alist))) (\.body (cdr (assq 'body alist)))) (insert (format " (%s) → %s\n" \.score (if (member \.author md4rd--fool-list) md4rd--fool-text (md4rd--greentext \.body))))))
  (let-alist comment (insert (format " (%s) → %s\n" \.score (if (member \.author md4rd--fool-list) md4rd--fool-text (md4rd--greentext \.body)))))
  (progn (let-alist comment (insert (format " (%s) → %s\n" \.score (if (member \.author md4rd--fool-list) md4rd--fool-text (md4rd--greentext \.body))))))
  (if comment (progn (let-alist comment (insert (format " (%s) → %s\n" \.score (if (member \.author md4rd--fool-list) md4rd--fool-text (md4rd--greentext \.body)))))))
  (when comment (let-alist comment (insert (format " (%s) → %s\n" \.score (if (member \.author md4rd--fool-list) md4rd--fool-text (md4rd--greentext \.body))))))
  (let ((comment (md4rd--find-comment-by-name item))) (when comment (let-alist comment (insert (format " (%s) → %s\n" \.score (if (member \.author md4rd--fool-list) md4rd--fool-text (md4rd--greentext \.body)))))))
  (lambda (item indent) (let ((comment (md4rd--find-comment-by-name item))) (when comment (let-alist comment (insert (format " (%s) → %s\n" \.score (if ... md4rd--fool-text ...)))))))(t1_hghv8la 4)
  #f(compiled-function (item indent) #<bytecode -0x152bcbcf7b1be6f5>)(t1_hghv8la 4)
  #f(compiled-function (item indent) #<bytecode 0xe168bea6d3b1301>)(t1_hghv8la 4)
  hierarchy-labelfn-to-string(#f(compiled-function (item indent) #<bytecode 0xe168bea6d3b1301>) t1_hghv8la 4)
  #f(compiled-function (item indent children) #<bytecode 0x4ae418e76d9709d>)(t1_hghv8la 4 nil)
  hierarchy-map-tree(#f(compiled-function (item indent children) #<bytecode 0x4ae418e76d9709d>) #s(hierarchy :roots nil :parents #<hash-table equal 45/65 0x6a74722f85> :children #<hash-table equal 26/65 0x6a74724211> :seen-items #<hash-table equal 46/65 0x6a7473f369>) t1_hghv8la 4)
  #f(compiled-function (child) #<bytecode -0x51b9fd55fcbca7c>)(t1_hghv8la)
  hierarchy-map-tree(#f(compiled-function (item indent children) #<bytecode 0x4ae418e76d9709d>) #s(hierarchy :roots nil :parents #<hash-table equal 45/65 0x6a74722f85> :children #<hash-table equal 26/65 0x6a74724211> :seen-items #<hash-table equal 46/65 0x6a7473f369>) t1_hghufmj 3)
  #f(compiled-function (child) #<bytecode -0x51b9fd55fcbd17c>)(t1_hghufmj)
  hierarchy-map-tree(#f(compiled-function (item indent children) #<bytecode 0x4ae418e76d9709d>) #s(hierarchy :roots nil :parents #<hash-table equal 45/65 0x6a74722f85> :children #<hash-table equal 26/65 0x6a74724211> :seen-items #<hash-table equal 46/65 0x6a7473f369>) t1_hghts4q 2)
  #f(compiled-function (child) #<bytecode -0x51b9fd55fcbb87c>)(t1_hghts4q)
  hierarchy-map-tree(#f(compiled-function (item indent children) #<bytecode 0x4ae418e76d9709d>) #s(hierarchy :roots nil :parents #<hash-table equal 45/65 0x6a74722f85> :children #<hash-table equal 26/65 0x6a74724211> :seen-items #<hash-table equal 46/65 0x6a7473f369>) t3_q63uw1 1)
  #f(compiled-function (child) #<bytecode -0x51b9fd55fcbb77c>)(t3_q63uw1)
  hierarchy-map-tree(#f(compiled-function (item indent children) #<bytecode 0x4ae418e76d9709d>) #s(hierarchy :roots nil :parents #<hash-table equal 45/65 0x6a74722f85> :children #<hash-table equal 26/65 0x6a74724211> :seen-items #<hash-table equal 46/65 0x6a7473f369>))
  hierarchy-convert-to-tree-widget(#s(hierarchy :roots nil :parents #<hash-table equal 45/65 0x6a74722f85> :children #<hash-table equal 26/65 0x6a74724211> :seen-items #<hash-table equal 46/65 0x6a7473f369>) #f(compiled-function (item indent) #<bytecode 0xe168bea6d3b1301>))
  hierarchy-tree-display(#s(hierarchy :roots nil :parents #<hash-table equal 45/65 0x6a74722f85> :children #<hash-table equal 26/65 0x6a74724211> :seen-items #<hash-table equal 46/65 0x6a7473f369>) #f(compiled-function (item indent) #<bytecode 0xe168bea6d3b1301>))
  md4rd--comments-show()
  md4rd--fetch-comments-callback(:data [((kind . "Listing") (data (after) (dist . 1) (modhash . "") (geo_filter . "") (children . [(... ...)]) (before))) ((kind . "Listing") (data (after) (dist) (modhash . "") (geo_filter . "") (children . [(... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...)]) (before)))] :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history (#s(request-response :status-code nil :history nil :data nil :error-thrown nil :symbol-status nil :url "http://reddit.com/r/emacs/comments/q63uw1/or..." :done-p nil :settings nil :-buffer #<killed buffer> :-raw-header "HTTP/1.1 301 Moved Permanently\nRetry-After: ..." :-timer nil :-backend curl)) :data [((kind . "Listing") (data (after) (dist . 1) (modhash . "") (geo_filter . "") (children . [...]) (before))) ((kind . "Listing") (data (after) (dist) (modhash . "") (geo_filter . "") (children . [... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...]) (before)))] :error-thrown nil :symbol-status success :url https://www\.reddit\.com/r/emacs/comments/q63uw1/orgroamui_file_previews_at_last/\.json :done-p nil :settings (:complete md4rd--fetch-comments-callback :sync nil :parser json-read :headers (("User-Agent" . "fun")) :error #f(compiled-function (&rest rest) #<bytecode 0x3ca51a6e935141a>) :url "http://reddit.com/r/emacs/comments/q63uw1/or..." :response #8 :encoding utf-8) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nConnection: keep-alive\nConte..." :-timer nil :-backend curl))
  apply(md4rd--fetch-comments-callback (:data [((kind . "Listing") (data (after) (dist . 1) (modhash . "") (geo_filter . "") (children . [(... ...)]) (before))) ((kind . "Listing") (data (after) (dist) (modhash . "") (geo_filter . "") (children . [(... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...)]) (before)))] :symbol-status success :error-thrown nil :response #s(request-response :status-code 200 :history (#s(request-response :status-code nil :history nil :data nil :error-thrown nil :symbol-status nil :url "http://reddit.com/r/emacs/comments/q63uw1/orgroamu..." :done-p nil :settings nil :-buffer #<killed buffer> :-raw-header "HTTP/1.1 301 Moved Permanently\nRetry-After: 0\nLoca..." :-timer nil :-backend curl)) :data [((kind . "Listing") (data (after) (dist . 1) (modhash . "") (geo_filter . "") (children . [...]) (before))) ((kind . "Listing") (data (after) (dist) (modhash . "") (geo_filter . "") (children . [... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...]) (before)))] :error-thrown nil :symbol-status success :url https://www\.reddit\.com/r/emacs/comments/q63uw1/orgroamui_file_previews_at_last/\.json :done-p nil :settings (:complete md4rd--fetch-comments-callback :sync nil :parser json-read :headers (("User-Agent" . "fun")) :error #f(compiled-function (&rest rest) #<bytecode 0x3ca51a6e935141a>) :url "http://reddit.com/r/emacs/comments/q63uw1/orgroamu..." :response #10 :encoding utf-8) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nConnection: keep-alive\nContent-Len..." :-timer nil :-backend curl)))
  request--callback(#<killed buffer> :complete md4rd--fetch-comments-callback :sync nil :parser json-read :headers (("User-Agent" . "fun")) :error #f(compiled-function (&rest rest) #<bytecode 0x3ca51a6e935141a>) :url "http://reddit.com/r/emacs/comments/q63uw1/orgroamu..." :response #s(request-response :status-code 200 :history (#s(request-response :status-code nil :history nil :data nil :error-thrown nil :symbol-status nil :url "http://reddit.com/r/emacs/comments/q63uw1/orgroamu..." :done-p nil :settings nil :-buffer #<killed buffer> :-raw-header "HTTP/1.1 301 Moved Permanently\nRetry-After: 0\nLoca..." :-timer nil :-backend curl)) :data [((kind . "Listing") (data (after) (dist . 1) (modhash . "") (geo_filter . "") (children . [(... ...)]) (before))) ((kind . "Listing") (data (after) (dist) (modhash . "") (geo_filter . "") (children . [(... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...) (... ...)]) (before)))] :error-thrown nil :symbol-status success :url https://www\.reddit\.com/r/emacs/comments/q63uw1/orgroamui_file_previews_at_last/\.json :done-p nil :settings (:complete md4rd--fetch-comments-callback :sync nil :parser json-read :headers (("User-Agent" . "fun")) :error #f(compiled-function (&rest rest) #<bytecode 0x3ca51a6e935141a>) :url "http://reddit.com/r/emacs/comments/q63uw1/orgroamu..." :response #15 :encoding utf-8) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nConnection: keep-alive\nContent-Len..." :-timer nil :-backend curl) :encoding utf-8)
  apply(request--callback #<killed buffer> (:complete md4rd--fetch-comments-callback :sync nil :parser json-read :headers (("User-Agent" . "fun")) :error #f(compiled-function (&rest rest) #<bytecode 0x3ca51a6e935141a>) :url "http://reddit.com/r/emacs/comments/q63uw1/orgroamu..." :response #s(request-response :status-code 200 :history (#s(request-response :status-code nil :history nil :data nil :error-thrown nil :symbol-status nil :url "http://reddit.com/r/emacs/comments/q63uw1/orgroamu..." :done-p nil :settings nil :-buffer #<killed buffer> :-raw-header "HTTP/1.1 301 Moved Permanently\nRetry-After: 0\nLoca..." :-timer nil :-backend curl)) :data [((kind . "Listing") (data (after) (dist . 1) (modhash . "") (geo_filter . "") (children . [...]) (before))) ((kind . "Listing") (data (after) (dist) (modhash . "") (geo_filter . "") (children . [... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ... ...]) (before)))] :error-thrown nil :symbol-status success :url https://www\.reddit\.com/r/emacs/comments/q63uw1/orgroamui_file_previews_at_last/\.json :done-p nil :settings #3 :-buffer #<killed buffer> :-raw-header "HTTP/1.1 200 OK\nConnection: keep-alive\nContent-Len..." :-timer nil :-backend curl) :encoding utf-8))
  request--curl-callback("http://reddit.com/r/emacs/comments/q63uw1/orgroamu..." #<process request curl> "finished\n")
  apply(request--curl-callback ("http://reddit.com/r/emacs/comments/q63uw1/orgroamu..." #<process request curl> "finished\n"))
  #f(compiled-function (&rest args2) #<bytecode -0xf1f0597f7dd0c82>)(#<process request curl> "finished\n")`

**Comment by ahungry** [comment]
md4rd--greentext was added by a contributor - I see they use a call to "map", which is an alias to cl-map, so I will update it as such and ensure cl-extra is in the requires.

**Comment by ahungry** [comment]
fc5fbf6

**Comment by nyambol** [comment]
Thank you.
