### ISSUE TITLE
Could not find package cl-extra

### ISSUE THREAD

**Issue by SqrtMinusOne** [ahungry/md4rd#34]
Hello,

I'm trying to Install the latest version of package with:
```lisp
(use-package md4rd
  :straight (:host github :repo "ahungry/md4rd"))
```
It fails with the following error:
```
Debugger entered--Lisp error: (error "Could not find package cl-extra. Updating recipe repositories: (org-elpa melpa gnu-elpa-mirror el-get emacsmirror-mirror) with ‘straight-pull-recipe-repositories’ may fix this")
  error("Could not find package %S. Updating recipe reposit..." cl-extra (org-elpa melpa gnu-elpa-mirror el-get emacsmirror-mirror))
  straight--convert-recipe(cl-extra "Building md4rd")
  straight-use-package(cl-extra nil nil "Building md4rd")
  straight--build-package((:host github :repo "ahungry/md4rd" :flavor melpa :package "md4rd" :type git :local-repo "md4rd") nil)
  #f(compiled-function () #<bytecode 0x1dbf8b4d0210bc11>)()
  straight--transaction-exec(use-package-\"e16de90e30791619d8273cd542d22b8c\"-nil-nil :now #f(compiled-function () #<bytecode 0x1dbf8b4d0210bc11>))
  straight-use-package((md4rd :host github :repo "ahungry/md4rd" :flavor melpa))
  (progn (straight-use-package '(md4rd :host github :repo "ahungry/md4rd" :flavor melpa)) (defvar use-package--warning180 #'(lambda (keyword err) (let ((msg (format "%s/%s: %s" ... keyword ...))) (display-warning 'use-package msg :error)))) (condition-case err (if (not (require 'md4rd nil t)) (display-warning 'use-package (format "Cannot load %s" 'md4rd) :error)) ((debug error) (funcall use-package--warning180 :catch err))))
  (progn (progn (straight-use-package '(md4rd :host github :repo "ahungry/md4rd" :flavor melpa)) (defvar use-package--warning180 #'(lambda (keyword err) (let ((msg ...)) (display-warning 'use-package msg :error)))) (condition-case err (if (not (require 'md4rd nil t)) (display-warning 'use-package (format "Cannot load %s" 'md4rd) :error)) ((debug error) (funcall use-package--warning180 :catch err)))))
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  command-execute(eval-last-sexp)
```
Rolling back to 8ed075874425c4aa1081608dd66f46e5dfa333c0 or declaring `cl-extra` as follows:
```lisp
(use-package cl-extra
  :straight (:type built-in))
```
seems to fix that.

That's probably not the indented behavior, but if it is, it might be wise to add the snippet above to the README.

Emacs version: GNU Emacs 28.0.60, commit 307d164c9c053501df8159719b3b502d720a945a
OS: GNU Guix, if that somehow matters

**Comment by ahungry** [comment]
This looks like your package manager ("straight") is encountering an error - I wonder why it did not encounter the error with the "cl-lib" reference I have in the Package-Requires: comment/meta section - I assume that is where this error is coming from, and not from the code section which has `(require 'cl-extra)`, as that is an Emacs builtin and should work normally (well, at least on my copy of 28.0.50)

**Comment by SqrtMinusOne** [comment]
I guess we'll see when Emacs 28 is released. If the problem persists there it would have to be addressed somehow.

**Comment by torgeir** [comment]
I also hit this today after reinstalling `emacs-plus@28` on homebrew. I have a similar use-package declaration for md4rd.

Edit:
I am also using straight.el, and the suggested fix works:

```emacs-lisp
(use-package cl-extra
  :straight (:type built-in))
```

**Comment by martianhi** [comment]
declaring `cl-extra` as a dependency is also making your package have status `incompat` on melpa. there's actually no reason to require it or have it as a dependency, declaring `cl-lib` alone should be enough, at least according to its author. do you have issues if you remove the require / dependency declaration?

**Comment by ahungry** [comment]
https://github.com/ahungry/md4rd/issues/33

was the reason it was added - I'll try removing it from the declaration section and push up a new commit.

**Comment by ahungry** [comment]
Let me know if next update is good, I adjusted in 6aa4fd6

**Comment by martianhi** [comment]
well, at least MELPA will let us update your package now @ahungry .

**Comment by SqrtMinusOne** [comment]
The latest version installs fine for me.

**Comment by ahungry** [comment]
Feel free to update here if I should re-open this, otherwise I'll consider it resolved.
