### ISSUE TITLE
the name

### ISSUE THREAD

**Issue by mooseyboots** [ahungry/md4rd#35]
while i'm briefly visiting yr repo, 

and i know there's the issue w the name,

but i also have repeatedly for example heard people saying things to the effect that 'there is no reddit client for emacs' or 'there should be an r c for e'

etc.

bit of a pity.

i even once forgot the name after installation, and therefore couldn't actually load it up! 

even `modeforreddit` would be better in this sense, as then it is locatable, whether in `M-x` or in a search engine, by searching for reddit (+ emacs say).

**Comment by ahungry** [comment]
This comes up as the first result when I google "Reddit mode for Emacs" - it is unfortunate, but noted in the readme - I would have much preferred keeping with Emacs convention and going with "reddit-mode".
