### ISSUE TITLE
Is there any setq sort=new option?

### ISSUE THREAD

**Issue by danrobi11** [ahungry/md4rd#36]
Hello. I Just found out about `md4rd`. Thank you much for this package. 

Unfortunately md4rd fetch the `top` section. The SubReddits new posts are in the `new` section :/

Is there any quick sort of `setq sort=new` available?

**Comment by ahungry** [comment]
Sorry for the delay here - just saw this issue.  I don't think so, although I wouldn't be opposed to it.

I'm a little vague on what matching the `top` implies though, a search-forward in the md4rd.el file doesn't have any matches for "top", and looking at the comments tied to a reddit thread, I don't see a "top" or "new" key in the JSON data structure.

For now, I'm going to close this, as I would be open to the PR, but won't be working on a feature update as requested at this time.
