### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [ahungry/md4rd#4]
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "hierarchy")
  require(hierarchy)
  eval-buffer(#<buffer  *load*-835842> nil "/home/psnc/.emacs.d/packages/redditor-mode/redditor.el" nil t)  ; Reading at buffer position 1263
  load-with-code-conversion("/home/psnc/.emacs.d/packages/redditor-mode/redditor.el" "/home/psnc/.emacs.d/packages/redditor-mode/redditor.el" nil t)
  require(redditor)
  eval-buffer(#<buffer  *load*> nil "/home/psnc/.emacs.d/init.el" nil t)  ; Reading at buffer position 5253
  load-with-code-conversion("/home/psnc/.emacs.d/init.el" "/home/psnc/.emacs.d/init.el" t t)
  load("/home/psnc/.emacs.d/init" t t)
  #[0 "^H\205\266^@     \306=\203^Q^@\307^H\310Q\202?^@ \311=\204^^^@\307^H\312Q\202?^@\313\307\314\315#\203*^@\316\202?^@\313\307\314\317#\203>^@\320\321\322!D\nB^R\323\2$
  command-line()
  normal-top-level()

**Comment by aancel** [comment]
Hello,
You are missing the hierachy package to be able to use redditor:
```
- M-x package-install
- hierarchy
```
I was also missing the request package on my side.
You have the list of required packages here: https://github.com/ahungry/redditor-mode/blob/bf925a95521a7edb9495f02d25b470df3ced2dbb/redditor.el#L10.

**Comment by ahungry** [comment]
Installing from MELPA should handle all the dependencies you need (until the next time I forget to add some).

Thanks for using the mode!
