### ISSUE TITLE
No thread comments are shown

### ISSUE THREAD

**Issue by lexa** [ahungry/md4rd#5]
In *subreddits* buffer, when I do a "RET" on the title name, I got a *hierarchy-tree* buffer, but the buffer is empty, there is no comments to the thread. In *message* buffer I have only one message:

    Fetching: /r/prolog/comments/7rf5ow/prolog_stateful_program_interpreter/

**Comment by lexa** [comment]
After playing a bit with the package I've noticed that

    (md4rd--fetch-comments "http://reddit.com/r/prolog/comments/7rf5ow/prolog_stateful_program_interpreter/.json")

Produces an empty hierarchy-tree buffer, but if backslash is removed from the URL, it works fine, like that:

    (md4rd--fetch-comments "http://reddit.com/r/prolog/comments/7rf5ow/prolog_stateful_program_interpreter.json")

**Comment by ahungry** [comment]
Are you sure this is broken?  You must visit a link that has comment discussion to see the thread, or else it will produce the empty comments page.

Can you give me a sample subreddit + link title you used to find this broken?

**Comment by ahungry** [comment]
Closing since we are safe from this issue now.
