### ISSUE TITLE
Cannot see my subs

### ISSUE THREAD

**Issue by Adocentyn** [ahungry/md4rd#8]
Hello, calling the md4rd mode (after having successfully logged in) will only display three subs (prolog, lisp and emacs). I'm only subscribed to one of them, /r/emacs, and I'm subscribed to many others. How do I refresh the subs list?

**Comment by ahungry** [comment]
At the moment I'm not requesting the subreddits via the login session, but rather the unauthed request, by way of the defcustom `md4rd-subs-active`, which starts set to those subreddits.

To request different ones, simply bind the variable to something else via setq or M-x customize.

I'll probably add the logged in call as well, with the 'front' or 'my' subreddit endpoint (which would be the customizations as they're stored on the reddit side.

**Comment by Adocentyn** [comment]
Thanks - I'll do that!

**Comment by NatHarari** [comment]
Hey there! I just installed it and I'm having the same thing happen. Just a tree with 3 subs (same as above). I'm new to this so I have absolutely no idea what your reply means, I'm afraid. How do I add my subs after I did the oauth login? Do I have to add them manually somehow? If so, how and where? :) (remember...I'm new...) :)

Thanks for any info!

**Comment by ahungry** [comment]
You define your own list of subscriptions in your config, it does not check what your reddit subscription settings are:

```lisp
(setq md4rd-subs-active '(emacs lisp+Common_Lisp prolog clojure))
```

In the setting there, that would subscribe me to /r/emacs, /r/lisp+Common_Lisp, /r/prolog and /r/clojure

**Comment by tulth** [comment]
In case it helps anyone in the future, I did the following:
- go to reddit.com/reddits
- Right click on "MultiReddit of your Subscriptions", copy the link address
- paste into emacs scratch buffer
- clean it up 
  - delete leading ```https://www.reddit.com/r/```
  -  and replace + with <space>
- use the resulting string as above:  ```(setq md4rd-subs-active '(<cleaned string>))```
